// Mock Data for User Portal (Electro Theme with 21 Craft & Tech Categories)

export const USER_CATEGORIES = [
  {
    id: '1',
    name: 'Puppetry',
    slug: 'puppetry',
    description: 'String puppets, shadow puppets, marionettes, and stage craft kits.',
    iconName: 'Theater',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80',
    count: 14,
  },
  {
    id: '2',
    name: 'Origami',
    slug: 'origami',
    description: 'Precision Japanese folding papers, toolkits, and 3D papercraft models.',
    iconName: 'FileText',
    image: 'https://images.unsplash.com/photo-1517697471339-4aa32003c11a?w=500&auto=format&fit=crop&q=80',
    count: 22,
  },
  {
    id: '3',
    name: 'Resin Art',
    slug: 'resin-art',
    description: 'Epoxy resins, silicone molds, mica pigments, and UV curing lamps.',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=500&auto=format&fit=crop&q=80',
    count: 38,
  },
  {
    id: '4',
    name: 'Papier Mâché',
    slug: 'papier-mache',
    description: 'Non-toxic pulp, mesh forms, adhesive binders, and sculpting paste.',
    iconName: 'Palette',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=500&auto=format&fit=crop&q=80',
    count: 11,
  },
  {
    id: '5',
    name: 'Clay Art',
    slug: 'clay-art',
    description: 'Polymer clay, air-dry clay, pottery tools, and mini sculpting kilns.',
    iconName: 'Circle',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=500&auto=format&fit=crop&q=80',
    count: 29,
  },
  {
    id: '6',
    name: 'Wood Working',
    slug: 'wood-working',
    description: 'Hand chisels, carving blocks, Japanese saws, and wood stains.',
    iconName: 'Hammer',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&auto=format&fit=crop&q=80',
    count: 45,
  },
  {
    id: '7',
    name: 'Metal',
    slug: 'metal',
    description: 'Sheet metals, soldering torches, wire bending jigs, and anvils.',
    iconName: 'Shield',
    image: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=500&auto=format&fit=crop&q=80',
    count: 19,
  },
  {
    id: '8',
    name: 'Digital Fabrication',
    slug: 'digital-fabrication',
    description: 'Laser engravers, CNC routers, vinyl cutters, and desktop plotters.',
    iconName: 'Cpu',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    count: 31,
  },
  {
    id: '9',
    name: '3D print',
    slug: '3d-print',
    description: 'FDM printers, SLA resin printers, PLA/PETG filaments, and nozzles.',
    iconName: 'Box',
    image: 'https://images.unsplash.com/photo-1631556097152-c39479bbf9f3?w=500&auto=format&fit=crop&q=80',
    count: 64,
  },
  {
    id: '10',
    name: 'Building Blocks',
    slug: 'building-blocks',
    description: 'Modular engineering bricks, architectural sets, and gear kits.',
    iconName: 'Grid',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500&auto=format&fit=crop&q=80',
    count: 52,
  },
  {
    id: '11',
    name: 'Stop Motion Animation',
    slug: 'stop-motion-animation',
    description: 'Armatures, rig arms, chroma key screens, and animation software packs.',
    iconName: 'Video',
    image: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=500&auto=format&fit=crop&q=80',
    count: 16,
  },
  {
    id: '12',
    name: 'Hydrophonics',
    slug: 'hydrophonics',
    description: 'NFT channels, water pumps, full-spectrum LED grow lights, and nutrients.',
    iconName: 'Droplets',
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=500&auto=format&fit=crop&q=80',
    count: 27,
  },
  {
    id: '13',
    name: 'Mechtronics (Robotic, AI, IOT & Electronics)',
    slug: 'mechtronics',
    description: 'Microcontrollers, sensor kits, servo motors, ESP32, and Raspberry Pi.',
    iconName: 'Bot',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=500&auto=format&fit=crop&q=80',
    count: 85,
  },
  {
    id: '14',
    name: 'Aero Modeling',
    slug: 'aero-modeling',
    description: 'Balsa wood RC plane kits, brushless motors, ESCs, and flight controllers.',
    iconName: 'Plane',
    image: 'https://images.unsplash.com/photo-1519074069444-1ba4ed168383?w=500&auto=format&fit=crop&q=80',
    count: 21,
  },
  {
    id: '15',
    name: 'Space Tech',
    slug: 'space-tech',
    description: 'Model rocket engines, telemetry sensors, satellite kits, and optics.',
    iconName: 'Rocket',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=80',
    count: 18,
  },
  {
    id: '16',
    name: 'Reverse Engineering',
    slug: 'reverse-engineering',
    description: 'Logic analyzers, 3D laser scanners, oscilloscope probes, and desoldering tools.',
    iconName: 'Search',
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=80',
    count: 15,
  },
  {
    id: '17',
    name: 'AVR (Audio Video Radio)',
    slug: 'avr',
    description: 'SDR receivers, audio amplifiers, video transmitter modules, and antennas.',
    iconName: 'Radio',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=500&auto=format&fit=crop&q=80',
    count: 33,
  },
  {
    id: '18',
    name: 'AR/VR',
    slug: 'ar-vr',
    description: 'Haptic gloves, tracking pucks, spatial depth cameras, and VR lenses.',
    iconName: 'Glasses',
    image: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=500&auto=format&fit=crop&q=80',
    count: 24,
  },
  {
    id: '19',
    name: 'Vinyl Art',
    slug: 'vinyl-art',
    description: 'Custom art vinyl blanks, adhesive films, weeding tools, and heat presses.',
    iconName: 'Disc',
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=500&auto=format&fit=crop&q=80',
    count: 26,
  },
  {
    id: '20',
    name: 'Print & Packaging',
    slug: 'print-packaging',
    description: 'Screen printing carousels, die cutters, eco box makers, and foil stampers.',
    iconName: 'Printer',
    image: 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?w=500&auto=format&fit=crop&q=80',
    count: 40,
  },
  {
    id: '21',
    name: 'Sublimation',
    slug: 'sublimation',
    description: 'Sublimation printers, specialized inks, blank mugs, t-shirts, and heat tapes.',
    iconName: 'Flame',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500&auto=format&fit=crop&q=80',
    count: 35,
  },
];

export const USER_PRODUCTS = [
  {
    id: 'prod-3d-1',
    name: 'Creality Ender-3 V3 SE High-Speed 3D Printer',
    categorySlug: '3d-print',
    categoryName: '3D print',
    price: 249.00,
    oldPrice: 299.00,
    rating: 4.8,
    reviewsCount: 142,
    stock: 25,
    isFeatured: true,
    isDealOfDay: true,
    soldCount: 38,
    totalDealStock: 50,
    badge: 'HOT DEAL',
    sku: '3D-END3-01',
    image: 'https://images.unsplash.com/photo-1631556097152-c39479bbf9f3?w=600&auto=format&fit=crop&q=80',
    description: 'Auto-leveling dual Z-axis 250mm/s high speed FDM 3D printer for precision maker models and rapid prototyping.',
  },
  {
    id: 'prod-3d-2',
    name: 'Elegoo Saturn 3 Ultra 12K SLA Resin Printer',
    categorySlug: '3d-print',
    categoryName: '3D print',
    price: 499.00,
    oldPrice: 569.00,
    rating: 4.9,
    reviewsCount: 89,
    stock: 12,
    isFeatured: true,
    badge: '12K RESOLUTION',
    sku: '3D-SAT3-02',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    description: '10-inch 12K mono LCD screen resin printer for miniature figures, jewelry, and ultra-detailed art models.',
  },
  {
    id: 'prod-mech-1',
    name: 'Arduino Ultimate Robotics Starter Kit with ESP32',
    categorySlug: 'mechtronics',
    categoryName: 'Mechtronics (Robotic, AI, IOT & Electronics)',
    price: 79.99,
    oldPrice: 99.99,
    rating: 4.7,
    reviewsCount: 230,
    stock: 40,
    isFeatured: true,
    isDealOfDay: true,
    soldCount: 42,
    totalDealStock: 60,
    badge: 'BEST SELLER',
    sku: 'MECH-ARD-01',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&auto=format&fit=crop&q=80',
    description: 'Comprehensive IoT & AI robotics kit including sensors, 4WD chassis, motor drivers, WiFi module, and step-by-step tutorials.',
  },
  {
    id: 'prod-mech-2',
    name: 'Raspberry Pi 5 8GB Starter Desktop Kit',
    categorySlug: 'mechtronics',
    categoryName: 'Mechtronics (Robotic, AI, IOT & Electronics)',
    price: 119.00,
    oldPrice: 139.00,
    rating: 5.0,
    reviewsCount: 310,
    stock: 18,
    isFeatured: true,
    badge: 'NEW',
    sku: 'MECH-RPI5-8G',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    description: 'Next generation Pi 5 computer with quad-core 64-bit Arm processor, dual 4K display support, active cooler, and 64GB MicroSD.',
  },
  {
    id: 'prod-resin-1',
    name: 'Crystal Clear Crystal Resin 1:1 Epoxy Kit (2 Gallons)',
    categorySlug: 'resin-art',
    categoryName: 'Resin Art',
    price: 89.50,
    oldPrice: 110.00,
    rating: 4.8,
    reviewsCount: 95,
    stock: 30,
    isFeatured: true,
    badge: 'TOP RATED',
    sku: 'RES-EPX-01',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    description: 'Zero VOC, UV resistant self-leveling epoxy resin for river tables, jewelry casting, coaster making, and high-gloss coating.',
  },
  {
    id: 'prod-wood-1',
    name: 'Narex Premium Woodworking Chisel Set of 6',
    categorySlug: 'wood-working',
    categoryName: 'Wood Working',
    price: 135.00,
    oldPrice: 160.00,
    rating: 4.9,
    reviewsCount: 64,
    stock: 15,
    isFeatured: true,
    badge: 'CRAFT CHOICE',
    sku: 'WOOD-CHIS-06',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format&fit=crop&q=80',
    description: 'Fine manganese steel woodworking bench chisels with hornbeam handles for furniture making and timber joinery.',
  },
  {
    id: 'prod-origami-1',
    name: 'Master Origami Deluxe Japanese Washi Paper 500 Sheets',
    categorySlug: 'origami',
    categoryName: 'Origami',
    price: 24.99,
    oldPrice: 34.99,
    rating: 4.6,
    reviewsCount: 112,
    stock: 55,
    badge: 'POPULAR',
    sku: 'ORI-PAP-500',
    image: 'https://images.unsplash.com/photo-1517697471339-4aa32003c11a?w=600&auto=format&fit=crop&q=80',
    description: 'Dual-sided vibrant Japanese patterned folding paper for geometric modular origami, cranes, and paper architecture.',
  },
  {
    id: 'prod-clay-1',
    name: 'Mont Marte 48 Colors Polymer Clay Tool Set',
    categorySlug: 'clay-art',
    categoryName: 'Clay Art',
    price: 36.00,
    oldPrice: 48.00,
    rating: 4.7,
    reviewsCount: 78,
    stock: 22,
    badge: 'SALE',
    sku: 'CLAY-POLY-48',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&auto=format&fit=crop&q=80',
    description: 'Bake-able soft polymer clay with 19 carving tools, jewelry accessories, and portable carrying box.',
  },
  {
    id: 'prod-space-1',
    name: 'Estes Alpha III Rocketry Launch System Kit',
    categorySlug: 'space-tech',
    categoryName: 'Space Tech',
    price: 54.99,
    oldPrice: 69.99,
    rating: 4.9,
    reviewsCount: 51,
    stock: 14,
    isDealOfDay: true,
    soldCount: 12,
    totalDealStock: 25,
    badge: 'SPACE KIT',
    sku: 'SPC-RCK-01',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    description: 'Complete high-altitude model rocket launch controller system with recovery parachute, launch pad, and safety key.',
  },
  {
    id: 'prod-aero-1',
    name: 'Balsa Wood RC Trainer Airplane Build Kit 1.2m',
    categorySlug: 'aero-modeling',
    categoryName: 'Aero Modeling',
    price: 129.99,
    oldPrice: 159.99,
    rating: 4.8,
    reviewsCount: 39,
    stock: 8,
    badge: 'BUILD KIT',
    sku: 'AERO-PLN-120',
    image: 'https://images.unsplash.com/photo-1519074069444-1ba4ed168383?w=600&auto=format&fit=crop&q=80',
    description: 'Laser-cut balsa wood RC airplane model kit complete with landing gear, hardware pack, and detailed scaling blueprints.',
  },
  {
    id: 'prod-hydro-1',
    name: 'Automated DWC Hydroponics 4-Bucket Grow System',
    categorySlug: 'hydrophonics',
    categoryName: 'Hydrophonics',
    price: 149.00,
    oldPrice: 189.00,
    rating: 4.7,
    reviewsCount: 88,
    stock: 19,
    badge: 'GREEN TECH',
    sku: 'HYD-DWC-04',
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80',
    description: 'Deep Water Culture recirculating hydroponics kit with air pump, clay pebbles, water level indicator, and nutrient starter.',
  },
  {
    id: 'prod-arvr-1',
    name: 'Ultraleap Leap Motion Controller 2 VR Tracking Mount',
    categorySlug: 'ar-vr',
    categoryName: 'AR/VR',
    price: 199.00,
    oldPrice: 229.00,
    rating: 4.9,
    reviewsCount: 47,
    stock: 11,
    badge: 'VR TRACKING',
    sku: 'VR-LEAP-02',
    image: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=600&auto=format&fit=crop&q=80',
    description: 'Optical hand tracking camera module for VR headsets, interactive museum displays, and spatial computing interfaces.',
  },
  {
    id: 'prod-sub-1',
    name: 'Epson SureColor Sublimation Printer Package + Heat Press',
    categorySlug: 'sublimation',
    categoryName: 'Sublimation',
    price: 599.00,
    oldPrice: 699.00,
    rating: 5.0,
    reviewsCount: 76,
    stock: 7,
    isFeatured: true,
    badge: 'BUSINESS BUNDLE',
    sku: 'SUB-EPS-F170',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
    description: 'Turnkey sublimation printing system with 15x15 heat press machine, heat tape, transfer papers, and full ink bottles.',
  },
  {
    id: 'prod-block-1',
    name: 'Technic Motorized Mechanical Gearbox Engineering Set',
    categorySlug: 'building-blocks',
    categoryName: 'Building Blocks',
    price: 84.99,
    oldPrice: 109.99,
    rating: 4.8,
    reviewsCount: 165,
    stock: 33,
    badge: 'STEM TOY',
    sku: 'BLK-TEC-100',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80',
    description: '1,450-piece motorized engineering block kit featuring working pistons, differential gears, and remote control receiver.',
  },
];
